# Generated by Django 3.1.7 on 2021-03-24 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin1', '0002_auto_20210324_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_id',
        ),
    ]
